# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fV79_uwhWUqQ4D-3iP0smbV2EqpcXD0f
"""

a = [1,2,3,4,5]

cnt = 0
for i in a:
  cnt+=i

for g in a:
  for j in a:
     cnt+=j
